### ISSUE TITLE
Group dependabot PRs

### ISSUE THREAD

**Issue by cremich** [cremich/kiko-backend#14]
Seems not to be the case, that dependabot is able to create consolidated PRs. Only updating one CDK lib might be not recommended and increases the risk of test errors. But I found this here:

https://www.hrvey.com/blog/combine-dependabot-prs

Would be cool to have something similar. 

__Originally posted by @cremich in https://github.com/cremich/kiko-backend/pull/8#issuecomment-822471502__

**Comment by timvancleef** [comment]
Wow... this is more complexe than i thought and i cant really find a good way of testing it.
All `@aws-cdk` have to be updated simultaneously otherwise `npm run build` will fail, due to peer dependency mismatches.

My take would currently be:
* ignore this combine-prs action
* exclude `@aws-cdk` dependencies from dependabot (and update them manually)
* see how noisy this actually will be (maybe it is ok for now)
* if it is too noisy take a look into [renovatebot](https://docs.renovatebot.com/) which is also free and easy to integrate

Renovatebot has out-of-the-box support for monorepos and will create consolidated PRs for them (in this case for `@aws-cdk`).

Would that ok with you @cremich?

**Comment by cremich** [comment]
Sounds like a plan. I like your proposal. 

Could you also exclude the aws-sdk? We use the one that is provided by the lambda runtime by default. 
Updating this might bring us in the position to use a newer one during development compared to runtime.

**Comment by cremich** [comment]
I created a new issue to tackle your proposals. Let's close this one.
